# Top-level configuration
name = "tempmail" # Ganti dengan nama proyek Anda jika berbeda
main = "src/workers/email-parser.ts" # Path ke file worker utama Anda
compatibility_date = "2024-07-10" # Tanggal hari ini

# Konfigurasi untuk D1 Database
[[d1_databases]]
binding = "INBOX_DB"
database_name = "tempemail"
database_id = "80ff2455-3530-4615-af55-e17ee16ba7a5"

# Konfigurasi untuk KV Namespace (backup/fallback)
[[kv_namespaces]]
binding = "INBOX_KV"
id = "5d8db901d3ef49cd896b903d90eb20fe"